configmap:
    data:
        - name: "message"
          value: "Hello World"
        - name: "loglevel"
          value: "info"
        - name: "format"
          value: "json"
    config:
      ServerName: node001
      RunStatus: 1
service:
    https:
        port: 443
    http:
      port: 80
    labels:
        environment: dev
        application: nginx
    annotations:
        - name: "author"
          value: "Ahmed"
        - name: "role"
          value: "frontend"