configmap:
    data:
        - name: "message"
          value: "Hello World"
        - name: "loglevel"
          value: "info"
        - name: "format"
          value: "json"
    config:
      ServerName: node001
      RunStatus: 1
service:
    https:
      port: 443
      nodePort: 1111
    http:
      port: 8080
      nodePort: 2222
    labels:
        environment: dev
        application: redis
    annotations:
        - name: "author"
          value: "Ahmed"
        - name: "role"
          value: "frontend"