apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-my-service
    {{- if .Values.service.labels}}
    labels:
      {{- with .Values.service.labels }}
        environment: {{ .environment}}
        application: {{ .application }}
        {{- end }}
    {{- end }}
    annotations:
      {{- range .Values.service.annotations }}
      {{ .name }}: "{{ .value }}"
      {{- end }}
spec:
    type: NodePort
    selector:
        app: helloworld
    ports:
       {{- with .Values.service }}
        - name: https
          protocol: TCP
          port: {{ .https.port }}
          targetPort: 443
        {{- if and (ge .https.nodePort 30000.0) (le .https.nodePort 32000.0) }}
          nodePort: {{ .https.nodePort }}
        {{- else }}
          nodePort: 30001
        {{- end }}
        - name: http
          protocol: TCP
          port: {{ .http.port }}
          targetPort: 80
        {{- if and (ge .http.nodePort 30000.0) (le .http.nodePort 32000.0) }}
          nodePort: {{ .http.nodePort }}
        {{- else }}
          nodePort: 30002
        {{- end }}
       {{- end }}