apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-my-service
    {{- if .Values.service.labels}}
    labels:
        environment: {{ .Values.service.labels.environment}}
    {{- end }}
spec:
    selector:
        app: helloworld
    ports:
        {{- if .Values.service.https }}
        - name: https
          protocol: TCP
          port: {{ .Values.service.https.port }}
          targetPort: 443
        {{- else }}
        - name: http
          protocol: TCP
          port: {{ .Values.service.http.port }}
          targetPort: 80
        {{- end }}