apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-my-service
    {{- if .Values.service.labels}}
    labels:
      {{- with .Values.service.labels }}
        environment: {{ .environment}}
        application: {{ .application }}
        {{- end }}
    {{- end }}
    annotations:
      {{- range .Values.service.annotations }}
      {{ .name }}: "{{ .value }}"
      {{- end }}
spec:
    selector:
        app: helloworld
    ports:
       {{- with .Values.service }}
        - name: https
          protocol: TCP
          port: {{ .https.port | default 443 }}
          targetPort: 443
        - name: http
          protocol: TCP
          port: {{ required "Please add a valid HTTP port" .http.port }}
          targetPort: 80
       {{- end }}